name: Build and Push Docker Image

inputs:
  tag:
    description: 'The tag to release'
    required: true
  token:
    description: 'The GitHub token'
    required: true
  registory:
    description: 'The Docker registry'
    required: true
  username:
    description: 'The Docker registry username'
    required: true

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: "${{ inputs.registory }}/mirakc"
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.tag }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }}
          type=semver,pattern={{major}},value=${{ inputs.tag }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: mirakc
        file: mirakc/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
